// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApi.Data;

#nullable disable

namespace MovieApi.Migrations
{
    [DbContext(typeof(MovieApiContext))]
    [Migration("20260616122124_MovieSeeds")]
    partial class MovieSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("MovieApi.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keanu Reeves"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = new DateTime(1924, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marlon Brando"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = new DateTime(1974, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christian Bale"
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = new DateTime(1954, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Travolta"
                        });
                });

            modelBuilder.Entity("MovieApi.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreType = "Action"
                        },
                        new
                        {
                            Id = 2,
                            GenreType = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            GenreType = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            GenreType = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            GenreType = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            GenreType = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            GenreType = "Thriller"
                        });
                });

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 148,
                            GenreId = 2,
                            Title = "Inception",
                            Year = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Duration = 136,
                            GenreId = 2,
                            Title = "The Matrix",
                            Year = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Duration = 175,
                            GenreId = 3,
                            Title = "The Godfather",
                            Year = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Duration = 152,
                            GenreId = 1,
                            Title = "The Dark Knight",
                            Year = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Duration = 154,
                            GenreId = 3,
                            Title = "Pulp Fiction",
                            Year = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MovieApi.Models.MovieDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("MovieDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 160000000,
                            Language = "English",
                            MovieId = 1,
                            Synopsis = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO."
                        },
                        new
                        {
                            Id = 2,
                            Budget = 63000000,
                            Language = "English",
                            MovieId = 2,
                            Synopsis = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers."
                        },
                        new
                        {
                            Id = 3,
                            Budget = 6000000,
                            Language = "English",
                            MovieId = 3,
                            Synopsis = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son."
                        },
                        new
                        {
                            Id = 4,
                            Budget = 185000000,
                            Language = "English",
                            MovieId = 4,
                            Synopsis = "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice."
                        },
                        new
                        {
                            Id = 5,
                            Budget = 8000000,
                            Language = "English",
                            MovieId = 5,
                            Synopsis = "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption."
                        });
                });

            modelBuilder.Entity("MovieApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "A mind-bending masterpiece!",
                            MovieId = 1,
                            Rating = 5,
                            ReviewerName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "A groundbreaking sci-fi classic.",
                            MovieId = 2,
                            Rating = 4,
                            ReviewerName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "An iconic crime drama.",
                            MovieId = 3,
                            Rating = 5,
                            ReviewerName = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "A thrilling superhero film.",
                            MovieId = 4,
                            Rating = 5,
                            ReviewerName = "Dave"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "A stylish and influential film.",
                            MovieId = 5,
                            Rating = 4,
                            ReviewerName = "Eve"
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("MovieApi.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApi.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.HasOne("MovieApi.Models.Genre", "Genres")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("MovieApi.Models.MovieDetails", b =>
                {
                    b.HasOne("MovieApi.Models.Movie", null)
                        .WithOne("MovieDetails")
                        .HasForeignKey("MovieApi.Models.MovieDetails", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApi.Models.Review", b =>
                {
                    b.HasOne("MovieApi.Models.Movie", "Movies")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.Navigation("MovieDetails");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
